### ISSUE TITLE
No error handling for missing EndIfs?

### ISSUE THREAD

**Issue by nischalshrestha** [nischalshrestha/CogulatorPlus#3]

**Comment by prgoodwin** [comment]
This file and BranchingWrapperFunctionality both were approaches that ended up not working.  Both should be good to delete.  (There may still be one reference to BranchingWrapperFunctionality in Main that needs to be changed as well.)

**Comment by prgoodwin** [comment]
This is a lot harder than it sounds.  Syntax coloring is done during execution of the model, which means we color it as we see it.  GoTo statements allow for nonlinear execution, so an EndIf may not ever be executed if the GoTo jumps out of the if-Statement.  Example:

Goal: Search Next enemy
...*stuff happens here
If enemies areGone
*you are done
GoTo: EndOfFile
EndIf
GoTo Goal: Search Next enemy


In order to be able to color the if statement for a missing EndIf, we'd have to do a separate pass of coloring, which I'm not sure is possible given how colorization and execution are currently combined.

**Comment by nischalshrestha** [comment]
Hm okay, so in that case what is EndIf being used for? Is it necessary at all? I'm guessing you're using it denote the end of that if, but wondering what you do in case there is no EndIf for an If.

**Comment by prgoodwin** [comment]
If the if statement is false, the execution jumps to the line after the matching endIf.  It's handled in the parsing, so it doesn't error out if it doesn't find an endIf.  Instead, it just returns the last line and ends the model.

**Comment by nischalshrestha** [comment]
You're talking about for that particular example you just gave right? If there is more stuff after the If, and there is no EndIf, I assume the stuff after the if still gets processed?

**Comment by prgoodwin** [comment]
no, because the lines after the if is considered to be in the body of the if-statement.  The EndIf is the closing bracket that lets you leave an If-statement, so if it is missing, everything after the If is considered to be in the body and will only execute if it is true.

**Comment by nischalshrestha** [comment]
Ah gotcha! We can talk about it but it may be something to handle because you may still want stuff after it to be processed if the If is false.

**Comment by nischalshrestha** [comment]
Added error handling for this.
